# 使用pickle序列化numpy array

In [2]:
import pickle
import numpy as np

In [4]:
x = np.arange(10)

In [5]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
f = open('x.pkl', 'wb') # 写 write bin 写二进制模式

In [10]:
pickle.dump(x, f)  # 把 x放到f文件

In [11]:
!ls #查看目录

'ls' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [12]:
f = open('x.pkl', 'rb')  # 必须修改，下面才能读load

In [13]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

保存到硬盘 save,load加载

In [6]:
np.save('one_array', x)

In [ ]:
!ls

In [7]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
y = np.arange(20)

In [15]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
np.savez('two_array.npz', a=x, b=y)  # x长度10 y长度20  有了一个新名字a,b

In [32]:
!ls

'ls' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [33]:
c = np.load('two_array.npz')

In [34]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])