# 快速创建数组

In [1]:
import numpy as np

In [2]:
np.random.randn(10)

array([ 1.11728195,  0.97598885, -1.22620285,  0.11538154,  1.27015472,
       -0.78067693, -0.62302511,  0.69416028, -0.17542351,  0.57074936])

In [3]:
np.random.randint(10, size=(2,3))

array([[7, 8, 6],
       [2, 8, 2]])

In [4]:
np.random.randint(10, size=20) #一维 

array([0, 2, 8, 6, 9, 3, 2, 5, 9, 0, 2, 7, 3, 8, 9, 1, 5, 0, 5, 6])

In [5]:
np.random.randint(10, size=20).reshape(4, 5)

array([[3, 8, 9, 2, 8],
       [1, 3, 3, 3, 6],
       [8, 8, 5, 1, 5],
       [6, 8, 9, 9, 2]])

# 数组运算

In [6]:
a = np.random.randint(10, size=20).reshape(4, 5)

In [7]:
b = np.random.randint(10, size=20).reshape(4, 5)

In [8]:
a

array([[2, 5, 1, 1, 8],
       [9, 3, 2, 6, 4],
       [0, 8, 7, 5, 4],
       [1, 1, 6, 1, 2]])

In [9]:
b

array([[7, 2, 1, 5, 9],
       [3, 9, 2, 8, 5],
       [8, 9, 2, 5, 4],
       [3, 1, 8, 5, 0]])

In [10]:
a + b

array([[ 9,  7,  2,  6, 17],
       [12, 12,  4, 14,  9],
       [ 8, 17,  9, 10,  8],
       [ 4,  2, 14,  6,  2]])

In [11]:
a - b

array([[-5,  3,  0, -4, -1],
       [ 6, -6,  0, -2, -1],
       [-8, -1,  5,  0,  0],
       [-2,  0, -2, -4,  2]])

In [12]:
a * b

array([[14, 10,  1,  5, 72],
       [27, 27,  4, 48, 20],
       [ 0, 72, 14, 25, 16],
       [ 3,  1, 48,  5,  0]])

In [13]:
a / b

<ipython-input-13-d8e10abd5ab6>:1: RuntimeWarning: divide by zero encountered in true_divide
  a / b


array([[0.28571429, 2.5       , 1.        , 0.2       , 0.88888889],
       [3.        , 0.33333333, 1.        , 0.75      , 0.8       ],
       [0.        , 0.88888889, 3.5       , 1.        , 1.        ],
       [0.33333333, 1.        , 0.75      , 0.2       ,        inf]])

In [14]:
a ./ b

SyntaxError: invalid syntax (<ipython-input-14-8d4567574f92>, line 1)

In [17]:
a .* b

SyntaxError: invalid syntax (<ipython-input-17-9d26613e1334>, line 1)

In [18]:
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [19]:
a

array([[2, 5, 1, 1, 8],
       [9, 3, 2, 6, 4],
       [0, 8, 7, 5, 4],
       [1, 1, 6, 1, 2]])

In [20]:
np.mat(a)

matrix([[2, 5, 1, 1, 8],
        [9, 3, 2, 6, 4],
        [0, 8, 7, 5, 4],
        [1, 1, 6, 1, 2]])

# 矩阵的运算

In [21]:
A = np.mat(a)

In [22]:
B = np.mat(b)

In [23]:
A

matrix([[2, 5, 1, 1, 8],
        [9, 3, 2, 6, 4],
        [0, 8, 7, 5, 4],
        [1, 1, 6, 1, 2]])

In [24]:
B

matrix([[7, 2, 1, 5, 9],
        [3, 9, 2, 8, 5],
        [8, 9, 2, 5, 4],
        [3, 1, 8, 5, 0]])

In [25]:
A + B

matrix([[ 9,  7,  2,  6, 17],
        [12, 12,  4, 14,  9],
        [ 8, 17,  9, 10,  8],
        [ 4,  2, 14,  6,  2]])

In [26]:
A - B

matrix([[-5,  3,  0, -4, -1],
        [ 6, -6,  0, -2, -1],
        [-8, -1,  5,  0,  0],
        [-2,  0, -2, -4,  2]])

In [27]:
A * B

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [28]:
a = np.mat(np.random.randint(10, size=20).reshape(4, 5))
b = np.mat(np.random.randint(10, size=20).reshape(5, 4))

In [29]:
a  #矩阵乘法

matrix([[8, 8, 3, 0, 6],
        [4, 6, 4, 9, 3],
        [0, 4, 6, 4, 5],
        [1, 1, 7, 5, 6]])

In [30]:
b

matrix([[6, 2, 1, 0],
        [4, 7, 8, 3],
        [7, 9, 4, 7],
        [0, 1, 1, 1],
        [9, 1, 5, 6]])

In [31]:
a * b

matrix([[155, 105, 114,  81],
        [103,  98,  92,  73],
        [103,  91,  85,  88],
        [113,  83,  72,  93]])

# Array常用函数

In [32]:
a = np.random.randint(10, size=20).reshape(4, 5)

In [33]:
np.unique(a)

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a

array([[4, 2, 2, 7, 8],
       [5, 9, 0, 5, 0],
       [3, 4, 9, 4, 6],
       [2, 8, 8, 6, 9]])

In [35]:
sum(a)

array([14, 23, 19, 22, 23])

In [37]:
sum(a[0]) #行和

23

In [38]:
sum(a[:,0]) #列和

14

In [39]:
a.max()

9

In [40]:
max(a[0])

8

In [41]:
max(a[:,0])

5